services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  App\:
    resource: '../../src/*'
    exclude: '../../src/{Kernel.php,Domain/**/Model,Domain/**/ValueObject}'

  # Shopify Client
  App\Shared\Infrastructure\Shopify\ShopifyClient:
    arguments:
      $shopifyApiUrl: '%env(SHOPIFY_API_URL)%'
      $shopifyApiAccessToken: '%env(SHOPIFY_API_ACCESS_TOKEN)%'
      $shopifyApiDeliveryAccessToken: '%env(SHOPIFY_API_DELIVERY_ACCESS_TOKEN)%'
      $logger: '@monolog.logger.shopify'

  App\Shared\Infrastructure\Sellsy\SellsyAccessTokenClient:
    arguments:
      $sellsyAccessTokenUrl: '%env(SELLSY_ACCESS_TOKEN_URL)%'
      $sellsyApiKey: '%env(SELLSY_API_KEY)%'
      $sellsyApiSecret: '%env(SELLSY_API_SECRET)%'

  App\Shared\Infrastructure\Sellsy\SellsyClient:
    arguments:
      $sellsyApiUrl: '%env(SELLSY_API_URL)%'

