# Limiter le WebProfiler à l'environnement de développement uniquement
when@dev:
  web_profiler:
    toolbar: true
    intercept_redirects: false

  framework:
    profiler:
      only_exceptions: false
